### ISSUE TITLE
Difference between CN1WindowsPort and current CN1

### ISSUE THREAD

**Issue by PiotrZub** [Pmovil/CN1WindowsPort#1]
I try to use your port to run my app on Windows Phone. Till now I can't run any app with you port because of many errors ex. 
Error       Build action 'EmbeddedResource' is not supported by projects with an output type of 'appcontainerexe'
or
lack of interface IFileOpenPickerContinuable.

So below I write down some question about your port:
1. When I copy your port into CN1 source I find that many CN1 files is not present in your port. So what version of CN1 you use? 
2. Do you directly edit cs files or java sources? If cs file it is not easy to introduce new CN1 futures?
3. Can you clarify:
•Create a Windows Universal apps project, include these files
include mean copy all files to new Windows Universal project and and include it in Project
4. Do you use Windows Phone 8.1 Uniwersal Project or Windows 10?

**Comment by PiotrZub** [comment]
Now I try to build KitchenSink and received the same errors:
1>\psf\home\documents\visual studio 2015\Projects\KitchenSink\KitchenSink\src\com\codename1\impl\SilverlightImplementation.cs(56,99,56,125): error CS0246: The type or namespace name 'IFileOpenPickerContinuable' could not be found (are you missing a using directive or an assembly reference?)
 and
1>------ Build started: Project: KitchenSink, Configuration: Debug x86 ------
1>\psf\home\documents\visual studio 2015\Projects\KitchenSink\KitchenSink\Resources\AppResources.Designer.cs(16,173,16,181): error CS1061: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
1>\psf\home\documents\visual studio 2015\Projects\KitchenSink\KitchenSink\src\pisces\m\Matrix.cs(2865,5,2865,12): error CS0103: The name 'Console' does not exist in the current context
1>\psf\home\documents\visual studio 2015\Projects\KitchenSink\KitchenSink\src\pisces\m\Matrix.cs(2874,4,2874,11): error CS0103: The name 'Console' does not exist in the current context

I do sth wrong but what?

**Comment by PiotrZub** [comment]
So after a few days I can answer for some questions myself:
ad.3. We must copy the files to the new project then include them into project. Next for resources files we change its properties Build Action to Content and Copy to Output to Copy if newer.
CN1 AppResources.resx rename to AppResources.resw and change Build Action to PRIResouces.
ad.4. I think nowadays it is WP 8.1 Uniwesal Project but it can be converted to Windows 10.

The errors listed above and other need to be corrented in c# code so I think maybe it I should create pull request for it?

So manage to build KitchenSink demo and it is working much better that on CN1 port. **So thanks Fabricio for great work**.

Now I need to build our app [FMap](https://itunes.apple.com/bj/app/fmap-gps-navigate-find-your/id1030407707?mt=8) and I think I need to add some code to your port or correct bug. Is it possible to add correction to your port?

Ps Still I do not known answers for 1 and 2 question.

**Comment by FabricioCabeca** [comment]
Hi @PiotrZub , sorry for the late reply, I was traveling this weekend. So here are the answers !

1- This port has the files that we changed, mainly all java package and the relevant implementation files (I guess I should provide a better step by step with this one).
2- The implementation most be cs, it is the glue to the cn1 code, the generated code from the java package does have some optimizations that were done to validate our work, they will be done the right way by creating a proper native glue.

I am tinkering with the offline build tools and the bytecode translator to have a complete workflow, so it will be independent from the build server and easier to work with, as there were not too much volunteers and we were validating most of the port we weren't worrying with ease of build, now we feel it is time to have this complete workflow done. Any help will be much appreciated ;-)

**Comment by FabricioCabeca** [comment]
Oh, about corrections to our port, you can fork our project, update it with your changes and submit a pull request, if it is ok we accept and merge it

**Comment by FabricioCabeca** [comment]
Merged #2
