### ISSUE TITLE
Detailed description

### ISSUE THREAD

**Issue by arcovandervelden** [Pmovil/CN1WindowsPort#10]
Hi there,

Do you have a detailed description about howto use this port for CN1 ?
I don't understand what to do in steps 3 till 5 of your description.

1 Send a windows 8 build to the codename one cloud with sources included (pro subscription needed)
2 Download the source and replace the codename one files by the ones in this port
3 replace the auto-generated MainPage using our template
4 Create a Windows Universal apps project, include these files
5 add the required dependencies to the project (Win2D, Zxing, Facebook)

**Comment by FabricioCabeca** [comment]
Hi !

3 - Take a look at MainPage.xaml.cs.default and MainPage.xaml.default, yours should look like these
5 - You can add these dependencies using the nuget package manager

**Comment by arcovandervelden** [comment]
Thanks for your response, 
What about step 4 ?, howto create the project (the source already contains a project), how to "include these files"?
What version of Visual studio should I use ?
