### ISSUE TITLE
Visual studio version etc

### ISSUE THREAD

**Issue by arcovandervelden** [Pmovil/CN1WindowsPort#11]
Hi can you tell me what visual studio version to use and what kind of project to create (windows phone 8.0 or 8.1) ? Can you tell me what version of Win2D to use?

**Comment by FabricioCabeca** [comment]
You should use Windows Phone 8.1 (no Silverlight) and the latest Win2D, there is an old deprecated Win2D version available, don't use that one, use the 1.X

**Comment by FabricioCabeca** [comment]
Sorry for the late replies, I've been out of office and just came back

**Comment by arcovandervelden** [comment]
Unfortunately I don’t get it to work.
Can you explain in a bit more detail what exactly to do ?
I did the following steps.
1. ```
     Did a CN1 build with sources.
   ```
2. ```
     Downloaded the sources from the CN1 server.
   ```
3. ```
     Replaced the codenameone folder within src.com with the codenameone folder from your port.
   ```
4. ```
     Created a “Blank App (Universal Windows 8.1)” with Visual Studio 2015
   ```
5. ```
     Copied all folders from the generated CN1 project to the newly created project
   ```
6. ```
     Added Win2D, Facebook and Zxing to the newly created project
   ```
7. ```
     Changed my App.xaml,App.xaml.cs,MainPage.xaml and MainPage.xaml.cs according to your template (I hope I did this right)
   ```

When I try to compile I’m getting almost 200 errors.

Met vriendelijke groet,
Best regards,

Arco van der Velden
Consultant

[cid:image001.jpg@01CEF015.2D39B860]http://www.synobsys.nl/

Rivium 3e straat 23
2909 LH Capelle aan den IJssel
Telefoon: +31 10 458 55 32
Mobiel: +31 6 53 67 68 56
Internet: www.synobsys.nlhttp://www.synobsys.nl/
E-mail: avandervelden@synobsys.nlmailto:avandervelden@synobsys.nl

From: FabricioCabeca [mailto:notifications@github.com]
Sent: maandag 30 november 2015 15:46
To: Pmovil/CN1WindowsPort CN1WindowsPort@noreply.github.com
Cc: Arco van der Velden AvanderVelden@synobsys.nl
Subject: Re: [CN1WindowsPort] Visual studio version etc (#11)

You should use Windows Phone 8.1 (no Silverlight) and the latest Win2D, there is an old deprecated Win2D version available, don't use that one, use the 1.X

—
Reply to this email directly or view it on GitHubhttps://github.com/Pmovil/CN1WindowsPort/issues/11#issuecomment-160650338.

**Comment by FabricioCabeca** [comment]
Hi Arco,

without knowing what are the errors exactly it is a bit hard to help you. About the project, try compiling the Windows Phone project and not the entire solution.

**Comment by arcovandervelden** [comment]
Hi Fabricio,

Thanks for your response, in the mean time I have reduced the number of errors but still have some left, see errors below, do you have any idea?
Most of the errors are in files “generated” by Visual Studio.

Severity

Code

Description

Project

File

Line

Error

CS0102

The type 'App' already contains a definition for '_contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\ARM\Debug\App.g.i.cs

18

Error

CS0111

Type 'App' already defines a member called 'InitializeComponent' with the same parameter types

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\ARM\Debug\App.g.i.cs

22

Error

CS0102

The type 'App' already contains a definition for '_contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\App.g.i.cs

18

Error

CS0111

Type 'App' already defines a member called 'InitializeComponent' with the same parameter types

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\App.g.i.cs

22

Error

CS0102

The type 'MainPage' already contains a definition for 'LayoutRoot'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\MainPage.g.i.cs

18

Error

CS0102

The type 'MainPage' already contains a definition for '_contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\MainPage.g.i.cs

20

Error

CS0111

Type 'MainPage' already defines a member called 'InitializeComponent' with the same parameter types

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\MainPage.g.i.cs

24

Error

CS0121

The call is ambiguous between the following methods or properties: 'App.InitializeComponent()' and 'App.InitializeComponent()'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\App.xaml.cs

38

Error

CS0121

The call is ambiguous between the following methods or properties: 'MainPage.InitializeComponent()' and 'MainPage.InitializeComponent()'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\MainPage.xaml.cs

35

Error

CS0229

Ambiguity between 'MainPage.LayoutRoot' and 'MainPage.LayoutRoot'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\MainPage.xaml.cs

41

Error

CS0229

Ambiguity between 'App._contentLoaded' and 'App._contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\ARM\Debug\App.g.i.cs

24

Error

CS0229

Ambiguity between 'App._contentLoaded' and 'App._contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\ARM\Debug\App.g.i.cs

27

Error

CS0229

Ambiguity between 'MainPage._contentLoaded' and 'MainPage._contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\ARM\Debug\MainPage.g.i.cs

26

Error

CS0229

Ambiguity between 'MainPage._contentLoaded' and 'MainPage._contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\ARM\Debug\MainPage.g.i.cs

29

Error

CS0229

Ambiguity between 'MainPage.LayoutRoot' and 'MainPage.LayoutRoot'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\ARM\Debug\MainPage.g.i.cs

32

Error

CS0229

Ambiguity between 'App._contentLoaded' and 'App._contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\App.g.i.cs

24

Error

CS0229

Ambiguity between 'App._contentLoaded' and 'App._contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\App.g.i.cs

27

Error

CS0229

Ambiguity between 'MainPage._contentLoaded' and 'MainPage._contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\MainPage.g.i.cs

26

Error

CS0229

Ambiguity between 'MainPage._contentLoaded' and 'MainPage._contentLoaded'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\MainPage.g.i.cs

29

Error

CS0229

Ambiguity between 'MainPage.LayoutRoot' and 'MainPage.LayoutRoot'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\obj\Debug\MainPage.g.i.cs

32

Error

CS1061

'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\Resources\AppResources.Designer.cs

16

Error

Build action 'EmbeddedResource' is not supported by projects with an output type of 'appcontainerexe'.

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\Resources\AppResources.resx

0

Error

CS1503

Argument 1: cannot convert from 'Windows.UI.Xaml.Media.Imaging.WriteableBitmap' to 'ZXing.LuminanceSource'

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\src\AsyncPictureDecoderExtension.cs

57

Error

CS0234

The type or namespace name 'FacebookShare' does not exist in the namespace 'com.codename1.share' (are you missing an assembly reference?)

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\src\com\codename1\components\ShareButton.cs

50

Error

CS0234

The type or namespace name 'FacebookShare' does not exist in the namespace 'com.codename1.share' (are you missing an assembly reference?)

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\src\com\codename1\components\ShareButton.cs

51

Error

CS0103

The name 'Console' does not exist in the current context

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\src\pisces\m\Matrix.cs

2865

Error

CS0103

The name 'Console' does not exist in the current context

AALease.WindowsPhone

E:\OpenSource\CodenameOne\Projects\AALeaseWindowsPort\AALease\AALease\AALease.WindowsPhone\src\pisces\m\Matrix.cs

2874

Met vriendelijke groet,
Best regards,

Arco van der Velden
Consultant

[cid:image001.jpg@01CEF015.2D39B860]http://www.synobsys.nl/

Rivium 3e straat 23
2909 LH Capelle aan den IJssel
Telefoon: +31 10 458 55 32
Mobiel: +31 6 53 67 68 56
Internet: www.synobsys.nlhttp://www.synobsys.nl/
E-mail: avandervelden@synobsys.nlmailto:avandervelden@synobsys.nl

**Comment by FabricioCabeca** [comment]
Hi Arco, you should  also remove all the pisces files.
I'm not sure about these duplicate complaints, try targeting "i386 Simulator" or "ARM Device" and use nothing from the source of the build server except your files.

**Comment by akash-kubavat** [comment]
@arcovandervelden Hi I am wondering if you succeed with this windows patch or not! as I am also stucked in this windows builds. Kindly let me know if you succeed then I am keen to know your way.

**Comment by arcovandervelden** [comment]
Hi,

Didn’t get it working yet.
I think I’ll get working on it this week or next week.

Met vriendelijke groet,
Best regards,

Arco van der Velden
Consultant

[cid:image001.jpg@01CEF015.2D39B860]http://www.synobsys.nl/

Rivium 3e straat 23
2909 LH Capelle aan den IJssel
Telefoon: +31 10 458 55 32
Mobiel: +31 6 53 67 68 56
Internet: www.synobsys.nlhttp://www.synobsys.nl/
E-mail: avandervelden@synobsys.nlmailto:avandervelden@synobsys.nl

**Comment by FabricioCabeca** [comment]
Sorry guys for not giving a better how-to, I've just been too busy. Please, let me know if you succeed and where were the caveats so I can update it.

About its quality compared to the official one, its worth your efforts.

**Comment by arcovandervelden** [comment]
Still not able to get it working, can you please spend an hour of your time to produce a detailed description an what exactly to do from getting the source from the codenameone server to get this working.
Thanks in advance.

**Comment by FabioConceicao** [comment]
Please, take a look at the updated Readme, let me know if it doesn't work.
