### ISSUE TITLE
Provide status/coverage overview

### ISSUE THREAD

**Issue by sidiabale** [Pmovil/CN1WindowsPort#12]
Hi,

Would it be possible to provide an overview of what functionality is covered in this port w.r.t. the official CN1 Windows Port? That will help other developers quickly decide whether it's worth trying out and/or give some direction on areas in which they can contribute.

For instance, I'm curious if this port currently supports:
- Native code access via CN1 native interfaces
- FontImages

Cheers

**Comment by FabricioCabeca** [comment]
Hi, our focus is on quality of port and supporting features that we do use, and we use many of them. One fellow had different needs and contributed a lot to the port too. It is not easy to setup but should give you better quality in almost anything, so if you have the guts and want something that performs like the android or iOS ports you should definitively try it.

About your questions:
- Native code access: sort of works, but keep in mind these will require minor tweaks and native code that relies on Silverlight specific code will not work.
- FontImages: Haven't tried them, but they should work out of the box as we do have a nice TTF support.
