### ISSUE TITLE
Create offline build task for CN1WindowsPort in CN1Offline

### ISSUE THREAD

**Issue by PiotrZub** [Pmovil/CN1WindowsPort#16]
Hi,
I setup new repository with framework to create offline cross compling of java project:
https://github.com/ForAnn/CN1Offline
I try to create task for your port but it seems that it use quite old CN1 API (version 3.1 show 55% files are different). Do you have java sources for version used by your port?

Maybe your implementation will work with newer CN1 API? To check it I will need to know which files where modificated by your? Of course the most of com\codename1\impl\ but maybe others too?

**Comment by FabricioCabeca** [comment]
Hi @PiotrZub , I've been busy here as usual. We are going to update our app in the Windows Store this week and will update the sources to use the 3.3 release. After this I will try your offline build tools and if it works as expected I will remove the unneeded files here so we can make our projects work properly with each other and remove the build server dependency.

Please notice there are some core java classes in my port that are different from the ones generated by xmlvm, these should probably be added to your port too if you didn't do this already.

**Comment by PiotrZub** [comment]
Hi, so now all files you get from CN1 build (except your port of course) or you have any manual changed files?

**Comment by FabricioCabeca** [comment]
all files come from CN1 build, we just exclude pisces and write our files over. We would still need to generate project files though, it shouldn't be hard.

Btw, I've talked to Steve from CN1 last friday, they are writing a new port based in this one (but using IKVM instead of XMLVM), it would be nice to see what they have and maybe focus in this official work

**Comment by PiotrZub** [comment]
Thank you for information.

P.S. I hope that IKVM do not generate different code for each build like 
ParparVM do.
