### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by luiz04nl** [Pmovil/CN1WindowsPort#17]
it is possible to use native interfaces, native google maps plugin and URLImage.createToStorage?

**Comment by FabricioCabeca** [comment]
- Native interfaces: Yes, may require a bit of tweaking when using external libs, and remember it is not a Silverlight project.
- Native google maps plugin: I didn't test it, I believe it is not supported but the openstreetmap fallback should work.
- URLImage: works.
