### ISSUE TITLE
Problem when trying to use native interface

### ISSUE THREAD

**Issue by luiz04nl** [Pmovil/CN1WindowsPort#20]
Problem when trying to use native interface, the following code works perfectly on ios and android but generates failure CN1WindowsPort

**Implementation:**

```
    MyNative my = (MyNative) NativeLookup.create(MyNative.class);
    String retorno = "FALHA";
    if (my != null && my.isSupported()) {
        retorno = my.teste(1);
    }
```

**interface:**

public interface MyNative extends NativeInterface{ 

```
public String teste(int val);      
```

}

**native class:**

namespace br.com.liquidity.agenda.vilhena.nativeinterfaces{

```
using System;
using System.Windows;

public class MyNativeImpl {
public String  teste(int param) {
    return "OK";
}

public bool isSupported() {
    return true;
}
```

}
}

*_Error:
*_
Exception thrown: 'System.NullReferenceException' in Main.exe
Stack traces aren't supported at the moment
java.lang.NullPointerException: System.NullReferenceException: Object reference not set to an instance of an object.

   at java.lang.Class.newInstance()

   at com.codename1.system.NativeLookup.create(Class n1)

**Comment by FabricioCabeca** [comment]
Search for MyNativeImpl, it should implement MyNative

**Comment by luiz04nl** [comment]
I did not understand where exactly is the problem?

**Comment by luiz04nl** [comment]
The class was generated automatically by codename one

**Comment by FabricioCabeca** [comment]
Try this:

`public class MyNativeImpl : MyNative {`

**Comment by luiz04nl** [comment]
if I just add the implementation of  MyNative the build fails, noting that was automatically generated by codename one.

doing some tests in visual studio I got the following class:

using System;
using java.lang;

namespace br.com.liquidity.agenda.vilhena.nativeinterfaces
{

```
public class MyNativeImpl : MyNative
{

    public System.Object teste(System.Int32 n1)
    {
        return "OK";
    }

    public System.Boolean dial(java.lang.String n1)
    {
        return false;
    }

    public System.Object convertData(java.lang.String n1)
    {
        return "10/10/2050";
    }

    public System.Boolean isSupported()
    {
        return true;
    }
}
```

}

build but not work, there is a small example  that I use as a base?

**Comment by FabricioCabeca** [comment]
What was the error ?
