### ISSUE TITLE
FacebookImpl.cs compilation errors

### ISSUE THREAD

**Issue by PiotrZub** [Pmovil/CN1WindowsPort#5]
I look like there is no all classes:
src\com\codename1\social\FacebookImpl.cs(4,7,4,15): error CS0246: The type or namespace name 'Facebook' could not be found 
src\com\codename1\social\FacebookImpl.cs(40,61,40,89): error CS0246: The type or namespace name 'SessionStateChangedEventArgs'

Do you know how to 'convince' VS2015 to automatically include new classes after sync server?
A new file FacebookImpl.cs wasn't shown in solution despite setting show all files flag. I have to add it in csproj file.

**Comment by FabricioCabeca** [comment]
Hi PiotrZub, you may try to remove the old folder from project and drag and drop so it should update. There was a change in the cn1's facebook implementation, you may pull our latest code to be sure it is there.

**Comment by PiotrZub** [comment]
Thank for advices.
About error that it is not all errors. In FacebookImpl.cs you use classes (Facebook.Client.Controls, Facebook.Client.Controls.LoginButton, Sessions, SessionStateChangedEventArgs) which are not present on your repository.

**Comment by FabricioCabeca** [comment]
You are right, Facebook requires an external dependency that you can install via nuget package manager

**Comment by FabioConceicao** [comment]
Also, in order to use the Facebook support you must add a FacebookConfig.xml with your id like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<Extensions>
  <Facebook AppId="0000000000000000" />
</Extensions>
```

and then, in your Package.appxmanifest under Declarations you must add a new Protocol with name fb0000000000000000
